# Plot LIGO data

In this part of the tutorial, let us plot some data from the LIGO
observatory.  

#### Getting a LIGO dataset

Go to the the `week03` directory of your CICF repository clone, and
then run `wget` with the URL of the data set as its argument (as shown
below).

```console
cd ~/cicf/week03
wget https://gwosc.org/archive/data/S5/814743552/H-H2_LOSC_4_V1-815235072-4096.hdf5
```

That should download a file `H-H2_LOSC_4_V1-815235072-4096.hdf5`,
which is about 123MB in size.  This file is in a format called [HDF5],
commonly used to store scientific data.  We will use the Python h5py
package that we installed earlier to work with this file.

[HDF5]: https://en.wikipedia.org/wiki/Hierarchical_Data_Format

Open [4-plot-ligo-data.ipynb](./4-plot-ligo-data.ipynb) in your
Jupyter environment, and work through the notebook.





You should have downloaded a file named
`H-H2_LOSC_4_V1-815235072-4096.hdf5` from LIGO, following the README
of this week.  Let open this file using the h5py library that we had
installed earlier and explore the data in the file.

```{python}
import h5py
data = h5py.File('H-H2_LOSC_4_V1-815235072-4096.hdf5', 'r')
```

We can look at the dataset:

```{python}
for k in data.keys():
    print(k)
```

And:

```{python}
for k,v in data['meta'].items():
    print(k,v)
```

That is not quite what we want:

```{python}
for k,v in data['meta'].items():
    print(k,v[...])
```

Let us load some of the data into an array, and plot the array using
matplotlib:

```{python}
import matplotlib.pyplot as plt

strain = data['strain']['Strain']
N = 5000
plt.plot(range(N), strain[:N])
```

